#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-multcompView
Version  : 0.1.7
Release  : 7
URL      : https://cran.r-project.org/src/contrib/multcompView_0.1-7.tar.gz
Source0  : https://cran.r-project.org/src/contrib/multcompView_0.1-7.tar.gz
Summary  : Visualizations of Paired Comparisons
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : clr-R-helpers

%description
p-values or a correlation, difference, or distance
    matrix into a display identifying the pairs for
    which the differences were not significantly
    different.  Designed for use in conjunction with
    the output of functions like TukeyHSD, dist{stats},
    simint, simtest, csimint, csimtest{multcomp},
    friedmanmc, kruskalmc{pgirmess}.

%prep
%setup -q -c -n multcompView

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523743300

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1523743300
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library multcompView
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library multcompView
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library multcompView
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library multcompView|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/multcompView/DESCRIPTION
/usr/lib64/R/library/multcompView/INDEX
/usr/lib64/R/library/multcompView/Meta/Rd.rds
/usr/lib64/R/library/multcompView/Meta/features.rds
/usr/lib64/R/library/multcompView/Meta/hsearch.rds
/usr/lib64/R/library/multcompView/Meta/links.rds
/usr/lib64/R/library/multcompView/Meta/nsInfo.rds
/usr/lib64/R/library/multcompView/Meta/package.rds
/usr/lib64/R/library/multcompView/NAMESPACE
/usr/lib64/R/library/multcompView/R/multcompView
/usr/lib64/R/library/multcompView/R/multcompView.rdb
/usr/lib64/R/library/multcompView/R/multcompView.rdx
/usr/lib64/R/library/multcompView/doc/VisualizingPairedComparisons.doc
/usr/lib64/R/library/multcompView/doc/VisualizingPairedComparisons.pdf
/usr/lib64/R/library/multcompView/doc/VisualizingPairedComparisons.ppt
/usr/lib64/R/library/multcompView/help/AnIndex
/usr/lib64/R/library/multcompView/help/aliases.rds
/usr/lib64/R/library/multcompView/help/multcompView.rdb
/usr/lib64/R/library/multcompView/help/multcompView.rdx
/usr/lib64/R/library/multcompView/help/paths.rds
/usr/lib64/R/library/multcompView/html/00Index.html
/usr/lib64/R/library/multcompView/html/R.css
