#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-multcompView
Version  : 0.1.8
Release  : 19
URL      : https://cran.r-project.org/src/contrib/multcompView_0.1-8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/multcompView_0.1-8.tar.gz
Summary  : Visualizations of Paired Comparisons
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : buildreq-R

%description
1. Put any C/C++/Fortran code in 'src'
2. If you have compiled code, add a .First.lib() function in 'R'
to load the shared library
3. Edit the help file skeletons in 'man'
4. Run R CMD build to create the index files
5. Run R CMD check to check the package
6. Run R CMD build to make the package file

%prep
%setup -q -c -n multcompView

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576779825

%install
export SOURCE_DATE_EPOCH=1576779825
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library multcompView
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library multcompView
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library multcompView
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc multcompView || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/multcompView/DESCRIPTION
/usr/lib64/R/library/multcompView/INDEX
/usr/lib64/R/library/multcompView/Meta/Rd.rds
/usr/lib64/R/library/multcompView/Meta/features.rds
/usr/lib64/R/library/multcompView/Meta/hsearch.rds
/usr/lib64/R/library/multcompView/Meta/links.rds
/usr/lib64/R/library/multcompView/Meta/nsInfo.rds
/usr/lib64/R/library/multcompView/Meta/package.rds
/usr/lib64/R/library/multcompView/NAMESPACE
/usr/lib64/R/library/multcompView/R/multcompView
/usr/lib64/R/library/multcompView/R/multcompView.rdb
/usr/lib64/R/library/multcompView/R/multcompView.rdx
/usr/lib64/R/library/multcompView/help/AnIndex
/usr/lib64/R/library/multcompView/help/aliases.rds
/usr/lib64/R/library/multcompView/help/multcompView.rdb
/usr/lib64/R/library/multcompView/help/multcompView.rdx
/usr/lib64/R/library/multcompView/help/paths.rds
/usr/lib64/R/library/multcompView/html/00Index.html
/usr/lib64/R/library/multcompView/html/R.css
